version = "Two"
use_small_heuristics = "Max"
reorder_imports = true
wrap_comments = true
unstable_features = true
condense_wildcard_suffixes = true
merge_imports = true
tab_spaces = 2
indent_style="Block"
edition = "2018"