language: rust
rust:
  - stable
  - beta
  - nightly

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  allow_failures:
    - rust: [ nightly ]
  fast_finish: true

build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose