[package]
name = "sak-paxos"
version = "0.1.0"
authors = ["Galudisu <galudisu@gmail.com>"]
edition = "2018"
repository = "https://github.com/barudisshu/sak-paxos"
license = "MIT"

[badges]
travis-ci = { repository = "kennytm/cargo-kcov" }

[dependencies]
log = "0.4"
t_bang = "0.1.2"